name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: replace

      - name: Deploy to Live Server and install
        run: |
          echo "${{ SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 161.97.68.166 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no vulps@161.97.68.166 \
            'cd /var/www/html/GameSync && git remote -v && git pull &&
            composer install --optimize-autoloader --no-dev && npm install && npm run build &&
            php artisan config:clear && php artisan event:clear && php artisan route:clear && php artisan view:clear &&
            php artisan config:cache && php artisan event:cache && php artisan route:cache && php artisan view:cache &&
            php artisan migrate'
