name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Deploy to Live Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no actions@ajmcallister.co.uk \
            'cd /var/www/html/GameSync && sudo git pull'
